spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${LOCAL-DB-USERNAME}
    password: ${LOCAL-DB-PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true
      generate-ddl: true
    generate-ddl: true
    defer-datasource-initialization: true

  redis:
    port: ${REDIS-PORT}
    host: ${REDIS-HOST}

  jackson:
    property-naming-strategy: SNAKE_CASE

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

org:
  springframework:
    security:
      level: INFO

socket :
  port : 8081

jwt:
  header: ${HEADER}
  prefix : ${PREFIX}
  secret-key: ${JWT-SECRET}
  access-exp: 999999999 # ${ACCESS-EXP}
  refresh-exp: ${REFRESH-EXP}